name: Build SingleFile
on:
  push:
    branches:
      - main
jobs:
  build:
    env:
      BUILD_TYPE: REL
      SENTRY_URL: ${{ secrets.SENTRY_URL }}
      SENTRY_KEY: ${{ secrets.SENTRY_KEY }}
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          architecture: 'x64'
      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Shanghai"
          timezoneMacos: "Asia/Shanghai"
          timezoneWindows: "China Standard Time"
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Get yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build:singlefile
      
      - name: Rename
        run: mkdir dist/local && mv dist/index.html dist/local/cocogoat-web-local.html && mv dist/assets/*.exe dist/local/
      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: cocogoat-web
          path: dist/local/