name: Build Production
on:
  push:
    branches:
      - main
jobs:
  build:
    env:
      BUILD_TYPE: REL
      SENTRY_URL: ${{ secrets.SENTRY_URL }}
      SENTRY_KEY: ${{ secrets.SENTRY_KEY }}
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3
      - name: Unpack git objects
        run: |
          mv .git/objects/pack .
          git unpack-objects < pack/*.pack
          rm -rf pack
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          architecture: 'x64'
      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Shanghai"
          timezoneMacos: "Asia/Shanghai"
          timezoneWindows: "China Standard Time"
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Get yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: cocogoat-web
          path: dist/
      - name: Remove unused files
        run: | 
          rm -rf dist/assets/*.wasm
          rm -rf dist/assets/*.ort
          rm -rf dist/index.html
      - name: Keep index.json
        run: mv dist/index.json ./index.temp.json
      - name: Deploy static files
        uses: TencentCloud/cos-action@v1
        with:
          secret_id: ${{ secrets.COS_ID }}
          secret_key: ${{ secrets.COS_KEY }}
          cos_bucket: ${{ secrets.COS_BUCKET }}
          cos_region: ${{ secrets.COS_REGION }}
          local_path: dist
          remote_path: /
          clean: false
      - name: Deploy index.json
        uses: TencentCloud/cos-action@v1
        with:
          secret_id: ${{ secrets.COS_ID }}
          secret_key: ${{ secrets.COS_KEY }}
          cos_bucket: ${{ secrets.COS_BUCKET }}
          cos_region: ${{ secrets.COS_REGION }}
          local_path: index.temp.json
          remote_path: index.json
          clean: false